# Ford GoBike Share Analysis

## Consolidation of data

This will import all files from the data source and create one consolidate master csv.  This only needs to be run once each time the source data is updated, changed or refreshed.

In [1]:
# import all necessary packages and functions.
import csv
from datetime import datetime
import numpy as np
import pandas as pd
from IPython.display import display
import os

In [2]:
files = os.listdir("./source_files/")

li = []

delimiter = ';'

use_cols = ['duration_sec','start_time','end_time','start_station_id','start_station_name','start_station_latitude',
            'start_station_longitude','end_station_id','end_station_name','end_station_latitude',
            'end_station_longitude','bike_id','user_type']

dtypes = {'duration_sec':'int','start_time':'str','end_time':'str','start_station_id':pd.Int64Dtype(),'start_station_name':'str',
          'start_station_latitude':'float','start_station_longitude':'float','end_station_id':pd.Int64Dtype(),
          'end_station_name':'str','end_station_latitude':'float','end_station_longitude':'float',
          'bike_id':'int','user_type':'str'}

parse_dates = ['start_time','end_time']


for file in files:
    with open("./source_files/" + file, 'rb') as f_in:
        df = pd.read_csv(f_in, compression='zip', delimiter=delimiter, usecols = use_cols, dtype=dtypes, 
                         header=0, parse_dates=parse_dates, na_values=['', ' '])
        li.append(df)
    
trip_df = pd.concat(li, axis=0, ignore_index=True)        

display(trip_df.head(5))

,duration_sec,start_time,end_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type
0,80110,2017-12-31 16:57:39.654,2018-01-01 15:12:50.245,74,Laguna St at Hayes St,37.776435,-122.426244,43,San Francisco Public Library (Grove St at Hyde...,37.778768,-122.415929,96,Customer
1,78800,2017-12-31 15:56:34.842,2018-01-01 13:49:55.617,284,Yerba Buena Center for the Arts (Howard St at ...,37.784872,-122.400876,96,Dolores St at 15th St,37.766210,-122.426614,88,Customer
2,45768,2017-12-31 22:45:48.411,2018-01-01 11:28:36.883,245,Downtown Berkeley BART,37.870348,-122.267764,245,Downtown Berkeley BART,37.870348,-122.267764,1094,Customer
3,62172,2017-12-31 17:31:10.636,2018-01-01 10:47:23.531,60,8th St at Ringold St,37.774520,-122.409449,5,Powell St BART Station (Market St at 5th St),37.783899,-122.408445,2831,Customer
4,43603,2017-12-31 14:23:14.001,2018-01-01 02:29:57.571,239,Bancroft Way at Telegraph Ave,37.868813,-122.258764,247,Fulton St at Bancroft Way,37.867789,-122.265896,3167,Subscriber

In [3]:
trip_df['start_date'] = trip_df.start_time.dt.strftime('%Y-%m-%d')
trip_df['start_year'] = trip_df.start_time.dt.strftime('%Y')
trip_df['start_month'] = trip_df.start_time.dt.strftime('%m')
trip_df['start_hour'] = trip_df.start_time.dt.strftime('%H')
trip_df['start_weekday'] = trip_df.start_time.dt.strftime('%a')


trip_df['end_date'] = trip_df.end_time.dt.strftime('%Y-%m-%d')
trip_df['end_year'] = trip_df.end_time.dt.strftime('%Y')
trip_df['end_month'] = trip_df.end_time.dt.strftime('%m')
trip_df['end_hour'] = trip_df.end_time.dt.strftime('%H')
trip_df['end_weekday'] = trip_df.end_time.dt.strftime('%a')

In [1]:
trip_df.head()

NameError: name 'trip_df' is not defined

In [4]:
trip_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4740302 entries, 0 to 4740301
Data columns (total 23 columns):
duration_sec               int32
start_time                 datetime64[ns]
end_time                   datetime64[ns]
start_station_id           Int64
start_station_name         object
start_station_latitude     float64
start_station_longitude    float64
end_station_id             Int64
end_station_name           object
end_station_latitude       float64
end_station_longitude      float64
bike_id                    int32
user_type                  object
start_date                 object
start_year                 object
start_month                object
start_hour                 object
start_weekday              object
end_date                   object
end_year                   object
end_month                  object
end_hour                   object
end_weekday                object
dtypes: Int64(2), datetime64[ns](2), float64(4), int32(2), object(13)
memory usage: 804.7+ MB

In [6]:
trip_df.to_csv('./trip_master.csv.gz', encoding='utf-8', compression='gzip')